language: node_js
node_js:
  - 10

# os: osx

sudo: true
services:
  - docker

before_install:
  - docker build -t damian/docker -f Dockerfile.dev .

script:
  - docker run damian/docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-880924148831"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"