language: node_js
node_js:
  - 10

# os: osx

sudo: true
services:
  - docker

before_install:
  - docker build -t damian/docker -f Dockerfile.dev .

script:
  - docker run damian/docker npm run test -- --coverage